# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/anki_persistent_editor/gui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(347, 111)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 2)
        self.flipShortcut = QtWidgets.QLineEdit(Settings)
        self.flipShortcut.setObjectName("flipShortcut")
        self.gridLayout.addWidget(self.flipShortcut, 0, 1, 1, 2)
        self.flipLabel = QtWidgets.QLabel(Settings)
        self.flipLabel.setObjectName("flipLabel")
        self.gridLayout.addWidget(self.flipLabel, 0, 0, 1, 1)
        self.example = QtWidgets.QLabel(Settings)
        self.example.setObjectName("example")
        self.gridLayout.addWidget(self.example, 1, 0, 1, 3)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Ze Add Note Id Settings"))
        self.flipLabel.setText(_translate("Settings", "Shortcut for flipping card"))
        self.example.setText(_translate("Settings", "Examples: \"C\", \"Alt+C\", \"Ctrl+Alt+C\""))
